apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbg-python-app
  labels:
    app: python-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: python-app
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: eu.gcr.io/lbg-cloud-incubation/python-app:latest
        imagePolicy: Always
        ports:
        - containerPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: python-app-service
spec:
  type: ClusterIP
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 8081