apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-python-app
  labels:
    app: nginx-pyapp-custom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pyapp-custom
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx-pyapp-custom
    spec:
      containers:
      - name: nginx-pyapp-container
        image: eu.gcr.io/lbg-cloud-incubation/nginx-pyapp-custom:latest
        imagePolicy: Always
        ports:
        - containerPort: 81
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-pyapp-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-pyapp-custom
  ports:
  - protocol: TCP
    port: 81
    targetPort: 81