apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{namespace}}
data:
  default.conf: |
    server {
        listen 81;

        location / {
            proxy_pass http://python-app-service:8081/index.html;
        }
    }
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{namespace}}
  labels:
    name: {{namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-python-app
  namespace: {{namespace}}
  labels:
    app: nginx-pyapp-custom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pyapp-custom
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx-pyapp-custom
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: nginx-pyapp-container
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-pyapp-service
  namespace: {{namespace}}
spec:
  type: LoadBalancer
  selector:
    app: nginx-pyapp-custom
  ports:
  - protocol: TCP
    port: 81
    targetPort: 81