apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app-custom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app-custom
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx-app-custom
    spec:
      containers:
      - name: nginx-app-container
        image: poojasdocker2023/nginx-app-cutom:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-app-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-app-custom
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80